export const ADD_PASSWORD_SUCCESS = 'ADD_PASSWORD_SUCCESS';
export const GET_PASSWORDS_SUCCESS = 'GET_PASSWORDS_SUCCESS';
export const DEL_PASSWORD_SUCCESS = 'DEL_PASSWORD_SUCCESS';
export const EDIT_PASSWORD_SUCCESS = 'EDIT_PASSWORD_SUCCESS';